### ISSUE TITLE
About layout on iphoneX/XR

### ISSUE THREAD

**Issue by sunyajie0829** [Nets-mobile-acceptance/Netaxept-iOS-SDK#8] opened 2019-09-05 09:40 UTC
When used on iphoneX, the navigationController top and bottom is blank. When I return to my own interface, my own navigationContoller also becomes blank

**Comment by Miss-PiA** [comment] 2019-09-06 12:38
Hi @sunyajie0829, we couldn't reproduce this issue. Can you clarify what you mean by _blank_?

**Comment by sunyajie0829** [comment] 2019-09-09 01:35
Hi:
	In the Simple ,I just change background color of CheckoutViewController to red, u see top is red, then I click setting button ,
Click add to register a new card, after that ,click cancel to back to main page, but now ,top become to red, and I see it in debug view.
It’s should be red, why?
	in my project, my ui is showing normaly ,but after I present sdkcontroller, the hole app’s top  become white color just
Like forth pic.



In my app it’s like this:


	thank for your last reply.

**Comment by Miss-PiA** [comment] 2019-09-09 08:35
Hi @sunyajie0829, thank you for your email. The issue is fixed on the next SDK version. Please wait for the release not far long.

**Comment by sunyajie0829** [comment] 2019-09-10 09:24
glad to waitting for update

**Comment by Miss-PiA** [comment] 2019-09-24 12:44
The issue is resolved in the latest updated Version 1.4.0

**Closed as completed by Miss-PiA** 2019-09-24 12:44 UTC
