### ISSUE TITLE
netaxept-ios-sdk v2.7.0 has errors

### ISSUE THREAD

**Issue by cindyha** [Nets-mobile-acceptance/Netaxept-iOS-SDK#50] opened 2023-02-20 08:44 UTC
Hi,
I'm getting these error when building flutter app with netaxept-ios-sdk v2.7.0. Is anyone facing same issue:
![Screenshot 2023-02-20 at 09 23 13](https://user-images.githubusercontent.com/5300207/220055819-8d934594-e7c8-40a8-96b1-2150b761fa73.png)

**Comment by BuildManager-Nets** [comment] 2023-02-21 10:51
Hi Cindya,
Thank you for reporting the issue we will look into it.
One query is as per your screenshots you are able to download the Carthage for netaxept-ios-sdk v2.7.0 then the above error you are getting after the integration of SDK in your flutter app right or just you are integrating SDK by drag and drop framework in your flutter app.  

Thanks

**Comment by cindyha** [comment] 2023-02-27 10:48
Hi,
It happens after I dragged and dropped the framework into my flutter app. So when I start debugging the app, it shows popup like this:
![Screenshot 2023-02-27 at 11 47 26](https://user-images.githubusercontent.com/5300207/221544195-a5d75e59-1386-4d33-85ed-69944b37d572.png)

**Comment by BuildManager-Nets** [comment] 2023-03-03 09:37
Hi CIndya,

The above issue that you mention will get resolved by changing the name of Flatbutton and RaisedButton as it is deprecated.
So change FlatButton to TextButton and RaisedButton to ElevatedButton.

Also, we have checked there is no issue from the SDK side after integration it is building properly. Actually, the issue is from the sample implementation code which is an old one. Actively we are not supporting the sample code currently.
You will get a sample code updated in a future release.

Thanks

**Comment by cindyha** [comment] 2023-03-07 08:55
Awesome! Thank you!

**Comment by BuildManager-Nets** [comment] 2023-03-07 11:50
Hi Cindya,
Thank you for your reply for now I am closing this ticket. In case of any further questions or queries, you can reopen the ticket.

Thank you

**Closed as completed by BuildManager-Nets** 2023-03-07 11:50 UTC
