### ISSUE TITLE
Impossible to perform 3DS verification when SDK View Controllers are presented in Swift UI environment.

### ISSUE THREAD

**Issue by kodelit** [Nets-mobile-acceptance/Netaxept-iOS-SDK#52] opened 2023-10-30 13:10 UTC
## 1. SDK is loosing connection when app is going to background and returns error immediately after returning to the app from the background. It makes the 3DS verification impossible.

It's hard to verify for us to verify and confirm all issues with 3DS our users experienced because we have only the sandbox which simulates the 3DS response in the app.
However we had many reports from the users that they failed to finish 3DS which are suggesting SDK issue.

### 1.a SDK returns error immediately after returning to the app from background

This is what we could simply reproduce by just sending app to the background when on the SDK screen.
This error seams to be cause by loosing the connection/session when the app goes to the background. In that case SDK returns error.

We manage to temporarily fix the issue by using the background tasks. However background task gives us up to 30 seconds to perform the task, so user have to go back to the app in this time.

We suspect that the issue might be somehow related to the SwiftUI because there is no such issue in the old version of the app implemented with UIKit, and we are not using background tasks nor any background mode there.

### 1.b SDK presents blank screens after returning to the app from background.

This is what might happen if
- we don't use background tasks
- user did not manage to finish 3DS verification within 30 seconds (with background tasks).

We could not reproduce it in sandbox but screenshots are suggesting that it's SDK view.

<img width="375" alt="screenshot jpg-3" src="https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK/assets/11218364/ed2eb735-e31d-4596-863c-1c1cc5bd42fb"> <img width="375" alt="screenshot jpg-2" src="https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK/assets/11218364/beb77c32-6958-45d6-a5bf-cc653225e33e">

## 2. SwiftUI integration issue.

As I mention we suspect that this might be related to the SwiftUI because we had also other issues with the SDK and Swift UI integration involving blank screens which we manage to solve. 
I'm describing this to crate the context how we are using SDK with SwiftUI.

The first approach was to embed them in the UIViewControllerRepresentable in order to display as a SwiftUI view.
This approach however caused issues with presenting the content. In our cases both payment and registration did not work because some layout issue (blank screen) in the SDK view controllers.

That is why we implement work around.
We are presenting the SDK controllers using UIKit `present(_:animated:completion:)` method on some empty UIViewControllerRepresentable view embed in the SwiftUI view body.

It solved the presentation issue.

**Are there maybe examples of using the SDK with SwiftUI?**

**Comment by Miss-PiA** [comment] 2023-11-02 13:08
Hi @kodelit ,

Thanks a lot for providing thorough description of the issue for SwiftUI integration with our SDK! 

To be honest, we don't have any example to demonstrate SDK integration with SwiftUI specifically. Because, in theory, Apple ensures that UIKit and SwiftUI are interoperable and it is strange that 3DS works in old version with UIKit but not SwiftUI.  However, it is indeed the problem to not be possible to complete 3DS for card payment. We will investigation internally along with all your shared findings and hopefully we can identify the root cause and find the workaround/solution to address this issue. We will keep you posted if we have any updates.

**Comment by Miss-PiA** [comment] 2023-11-20 13:58
Hi @kodelit,

we are back with some outcome after our internal research about the issue. We create simple sample app in SwiftUI to recreate the problem you've reported but we can't reproduce it and SDK has no visible issues with 3DS Web View even when the app was put to background for significant time. We share our Sample App in the following repository: 
https://github.com/Nets-mobile-acceptance/SwiftUI-CardPayment-SampleApp/tree/main 

Please have a try. We also attached a video with working example of 3D Secure process here: https://github.com/Nets-mobile-acceptance/SwiftUI-CardPayment-SampleApp/blob/main/swiftUI_3DS.mov

**Comment by Miss-PiA** [comment] 2023-12-14 12:04
Hi @kodelit ,

Since we didn't hear any reply from you, we closed it for now and please reopen if the issue still exists.

Thanks!

**Closed as completed by Miss-PiA** 2023-12-14 12:04 UTC
