### ISSUE TITLE
Card number field has corrupted UI when entering AMEX card number 

### ISSUE THREAD

**Issue by jakobmygind** [Nets-mobile-acceptance/Netaxept-iOS-SDK#9] opened 2019-11-05 15:13 UTC
When I start to enter the Nets test AMEX card (375700000000002) the UI corrupts after entering the first two digits, thereby obscuring the card number. Note that of the cards I have tried, only AMEX elicits this response.

Tested on iPhone X, iOS 13.2, SDK version 1.5

![IMG_AA5DEE9D5EF4-1](https://user-images.githubusercontent.com/8362263/68219930-14065b80-ffe7-11e9-9602-dd09fd6e7d0a.jpg)

**Comment by jakobmygind** [comment] 2019-11-07 13:36
Not very quick response :(

**Comment by Nets-LAKA-Mobile-SDK** [comment] 2019-11-13 08:33
Hi @jakobmygind and sorry for the delay in answering on this issue. 
The root cause as been identified and we are re-defining the formatting of this icon. 
The fix will be included in our next release expected before the end of November.

**Comment by jakobmygind** [comment] 2019-11-13 10:54
@Tim-Badin ok, thanks!

**Comment by jakobmygind** [comment] 2019-11-26 10:56
@Tim-Badin Any news regarding ETA of this fix?

**Comment by Miss-PiA** [comment] 2019-11-26 10:59
Hi @jakobmygind,

We are running the release testing now and we will let you know as soon as we could release in public!

Best regards,
Miss PiA

**Comment by Nets-LAKA-Mobile-SDK** [comment] 2019-11-26 13:41
Hi @jakobmygind 
We are testing the new release now. It will be available the latest on Friday. 
If available before, we will notify you here.
Best,
Tim

**Comment by jakobmygind** [comment] 2019-11-26 17:04
@Miss-PiA @Tim-Badin Thank you both :)

**Comment by Nets-LAKA-Mobile-SDK** [comment] 2019-12-02 16:12
Hi @jakobmygind 
The fix was release and contain the following: 
•	Fixed issue with American Express icon covering card number text field on iOS 13+
•	Fixed app-crash when customizing placeholder attributes on iOS 13+
•	Fixed issue with incorrect cursor shift when editing diners club international card number
•	Improved PiA sample app and comments in source code for easier integration
Thank you for your patience,
Don't hesitate to let us know if you find any other issue,

Tim

**Comment by jakobmygind** [comment] 2019-12-02 16:26
@Tim-Badin Thanks!

**Closed as completed** 2019-12-02 16:27 UTC
